services:
  db:
    container_name: postgres
    image: postgres:15.1
    environment:
      POSTGRES_USER: steadypim
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped
  sp-api:
    container_name: sp-api
    image: steadypim/sp-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/customer
    ports:
      - "8088:8075"
    networks:
      - db
    depends_on:
      - db
    restart: unless-stopped
  sp-react:
    container_name: sp-react
    image: steadypim/sp-react
    build:
      context: frontend/sp-api
    ports:
      - "3000:5173"
    depends_on:
      - sp-api
    restart: unless-stopped
networks:
  db:
    driver: bridge

volumes:
  db: